In [ ]:
import numpy as np

1.a) độ dài của vector

In [ ]:
def compute_vector_length(vector):
  return np.linalg.norm(vector)
arr = np.array([-2,4,9,21])
compute_vector_length(arr)

23.280893453645632

1.b) phép tích vô hướng

In [ ]:
def compute_dot_product(v1,v2):
  return np.dot(v1,v2)
arr1 = np.array([0,1,-1,2])
arr2 = np.array([2,5,1,0])
compute_dot_product(arr1,arr2)

4

1. c) multiplying a vector by a matrix

In [ ]:
def matrix_multi_vector(matrix,vector):
  return np.dot(matrix,vector)
m1 = np.eye (2)
m1 = np. reshape (m1 ,( -1 ,4) ) [0]
m2 = np. array ([[1 , 1 , 1 , 1] ,[2 , 2 , 2 , 2] , [3 , 3 , 3 , 3] , [4 , 4 , 4 , 4]])
matrix_multi_vector(m1,m2)

array([5., 5., 5., 5.])

1.d)multiplying a matrix by a matrix

In [ ]:
def matrix_multi_matrix(m1,m2):
  return np.einsum("ij,jk",m1,m2)
m1 = np.array([[0,1,2],[2,-3,1]])
m2 = np.array([[1,-3],[6,1],[0,-1]])
matrix_multi_matrix(m1,m2)


[1. 0. 0. 1.]
[[1 1 1 1]
 [2 2 2 2]
 [3 3 3 3]
 [4 4 4 4]]


ValueError: einstein sum subscripts string contains too many subscripts for operand 0

1.e) Matrix inverse
 - Matrix A: **A**  $=\begin{bmatrix}-2&6\cr 8&-4\end{bmatrix}$, $A  \in R ^{2*2}$

 - Determinant of $A \in R^{2*2}$: $det(A) = (-2)\times(-4) - 8 \times 6 =-40$
 -$det(A) \neq0$ **A** is invertible
 - Inverse Matrix: $A^{-1} = 1/det(A)\begin{bmatrix}-4&-6\cr -8&-2\end{bmatrix}$


In [ ]:
def Matrix_inverse(matrix):
  determinant = matrix[0,0]*matrix[1,1]-matrix[0,1]*matrix[1,0]
  if determinant != 0:
    return (1/determinant)*np.array([[matrix[1,1],-matrix[0,1]],[-matrix[1,0],matrix[0,0]]])
  else:
    return "Matrix cannot be inversed"
arr = np.array([[-2,6],[8,-4]])
print(Matrix_inverse(arr))

[[0.1  0.15]
 [0.2  0.05]]
[[0.1  0.15]
 [0.2  0.05]]


In [ ]:
m1 = np. array ([[1 , 2] , [3 , 4]])
m1 = np. reshape (m1 ,( -1 ,4) , "F") [0]
m2 = np. array ([[1 , 1 , 1 , 1] ,[2 , 2 , 2 , 2] , [3 , 3 , 3 , 3] , [4 , 4 , 4 , 4]])
result = m1@m2
print ( result )

[29 29 29 29]
