In [2]:
import numpy as np

In [ ]:
# Bài 1 B)
def df_w(W):
  k = np.array([[0.2,4]])
  return W*k
def sgd(W,dW,lr):
  return W-lr*dW
def train_pl_1(optimizer,lr,epochs):
  W = np.array([-5,-2],dtype=np.float32)
  results = [W]

  for _ in range(epochs):
    dW = df_w(W)
    W = optimizer(W,dW,lr)
    results.append(W)
  return results
results = train_pl_1(sgd,0.4,30)
results

[array([-5., -2.], dtype=float32),
 array([[-4.6,  1.2]]),
 array([[-4.232, -0.72 ]]),
 array([[-3.89344,  0.432  ]]),
 array([[-3.5819648, -0.2592   ]]),
 array([[-3.29540762,  0.15552   ]]),
 array([[-3.03177501, -0.093312  ]]),
 array([[-2.78923301,  0.0559872 ]]),
 array([[-2.56609437, -0.03359232]]),
 array([[-2.36080682,  0.02015539]]),
 array([[-2.17194227, -0.01209324]]),
 array([[-1.99818689,  0.00725594]]),
 array([[-1.83833194, -0.00435356]]),
 array([[-1.69126538,  0.00261214]]),
 array([[-1.55596415, -0.00156728]]),
 array([[-1.43148702e+00,  9.40369969e-04]]),
 array([[-1.31696806e+00, -5.64221981e-04]]),
 array([[-1.21161061e+00,  3.38533189e-04]]),
 array([[-1.11468176e+00, -2.03119913e-04]]),
 array([[-1.02550722e+00,  1.21871948e-04]]),
 array([[-9.43466646e-01, -7.31231688e-05]]),
 array([[-8.67989314e-01,  4.38739013e-05]]),
 array([[-7.98550169e-01, -2.63243408e-05]]),
 array([[-7.34666155e-01,  1.57946045e-05]]),
 array([[-6.75892863e-01, -9.47676268e-06]]),
 arra

In [24]:
# Bài 2 B)
def df_w(W):
  k = np.array([[0.2,4]])
  return W*k
def sgd_momentum(W,V,dW,beta,lr):
  V_new = beta*V + (1-beta)*dW
  W_new = W - lr*V_new
  return W_new,V_new
def train_pl_2(optimizer,lr,epochs):
  V = np.array([0,0],dtype=np.float32)
  W = np.array([-5,-2],dtype=np.float32)
  beta = 0.5
  results = [W]
  for _ in range(epochs):
    dW = df_w(W)
    W,V = optimizer(W,V,dW,beta,lr)
    results.append(W)
  return results
results = train_pl_2(sgd_momentum,0.6,30)
results

[array([-5., -2.], dtype=float32),
 array([[-4.7,  0.4]]),
 array([[-4.268,  1.12 ]]),
 array([[-3.79592,  0.136  ]]),
 array([[-3.3321248, -0.5192   ]]),
 array([[-2.90029971, -0.22376   ]]),
 array([[-2.51036919,  0.192472  ]]),
 array([[-2.16478177,  0.1696216 ]]),
 array([[-1.86210116, -0.04534952]]),
 array([[-1.59903478, -0.09841566]]),
 array([[-1.37155951, -0.00684994]]),
 array([[-1.1755283 ,  0.04715285]]),
 array([[-1.006981  ,  0.01757082]]),
 array([[-0.86228849, -0.01830518]]),
 array([[-0.73820492, -0.01427696]]),
 array([[-0.63187084,  0.0048695 ]]),
 array([[-0.54079155,  0.00859933]]),
 array([[-4.62804416e-01,  1.45050014e-04]]),
 array([[-0.39604258, -0.00425615]]),
 array([[-0.33889911, -0.00134937]]),
 array([[-0.28999343,  0.00172326]]),
 array([[-0.24814098,  0.00119166]]),
 array([[-0.2123263 , -0.00050413]]),
 array([[-0.18167938, -0.00074707]]),
 array([[-1.55455157e-01,  2.79448010e-05]]),
 array([[-0.13301574,  0.00038192]]),
 array([[-1.13815082e-01,  1.00

In [20]:
# Bài 3 B)
def df_w(W):
  k = np.array([[0.2,4]])
  return W*k
def RMSProp(S,W,dW,decay_rate,learning_rate,e):
  S_new = decay_rate*S + (1-decay_rate)*(dW**2)
  W_new = W - learning_rate*(dW/np.sqrt(S_new+e))
  return S_new,W_new
def train_pl_3(optimizer,lr,epochs):
  S = np.array([0,0],dtype=np.float32)
  W = np.array([-5,-2],dtype=np.float32)
  decay_rate = 0.9
  e = 1e-6
  results = [W]
  for _ in range(epochs):
    dW = df_w(W)
    S,W = optimizer(S,W,dW,decay_rate,lr,e)
    results.append(W)
  return results
train_pl_3(RMSProp,0.3,30)

[array([-5., -2.], dtype=float32),
 array([[-4.05132145, -1.05131678]]),
 array([[-3.43519754, -0.59152343]]),
 array([[-2.95893693, -0.3294394 ]]),
 array([[-2.56546289, -0.17756482]]),
 array([[-2.22920552, -0.09163256]]),
 array([[-1.93626752, -0.04494499]]),
 array([[-1.67817686, -0.02081423]]),
 array([[-1.44934985, -0.00903559]]),
 array([[-1.24588199, -0.00364591]]),
 array([[-1.06490301, -0.00135351]]),
 array([[-9.04202260e-01, -4.56444431e-04]]),
 array([[-7.61996495e-01, -1.37562928e-04]]),
 array([[-6.36778499e-01, -3.62601019e-05]]),
 array([[-5.27215237e-01, -8.11337456e-06]]),
 array([[-4.32078505e-01, -1.47473412e-06]]),
 array([[-3.50198507e-01, -2.02783991e-07]]),
 array([[-2.80434649e-01, -1.84231187e-08]]),
 array([[-2.21659834e-01, -7.67742748e-10]]),
 array([[-1.72755512e-01,  7.80451998e-12]]),
 array([[-1.32615134e-01, -5.05794800e-13]]),
 array([[-1.00153779e-01,  6.19123501e-14]]),
 array([[-7.43217708e-02, -1.13373781e-14]]),
 array([[-5.41201278e-02,  2.8016

In [21]:
# Bài 4 b)
def df_W(W):
  k = np.array([[0.2,4]])
  return W*k
def Adam(W,S,V,dW,beta1,beta2,lr,e,t):
  V_new = beta1*V + (1-beta1)*dW
  S_new = beta2*S + (1-beta2)*(dW**2)
  V_corr = V_new/(1-beta1**t)
  S_corr = S_new/(1-beta2**t)
  W_new = W - lr*(V_corr/(np.sqrt(S_corr)+e))
  return W_new,V_new,S_new
def train_pl_4(optimizer,lr,epochs):
  S = np.array([0,0],dtype=np.float32)
  W = np.array([-5,-2],dtype=np.float32)
  V = np.array([0,0],dtype=np.float32)
  beta1 = 0.9
  beta2 = 0.999
  e = 1e-6
  results = [W]
  for t in range(epochs):
    dW = df_W(W)
    W,V,S = optimizer(W,S,V,dW,beta1,beta2,lr,e,t+1)
    results.append(W)
  return results
train_pl_4(Adam,0.2,30)

[array([-5., -2.], dtype=float32),
 array([[-4.8000002 , -1.80000002]]),
 array([[-4.60025478, -1.60082451]]),
 array([[-4.40094848, -1.40317262]]),
 array([[-4.20227764, -1.20787822]]),
 array([[-4.00445033, -1.01592745]]),
 array([[-3.80768638, -0.82847307]]),
 array([[-3.61221732, -0.64684159]]),
 array([[-3.41828623, -0.47252765]]),
 array([[-3.22614739, -0.30716934]]),
 array([[-3.03606592, -0.15249855]]),
 array([[-2.84831706, -0.01026326]]),
 array([[-2.66318543,  0.11787552]]),
 array([[-2.480964  ,  0.23046161]]),
 array([[-2.30195279,  0.3263587 ]]),
 array([[-2.12645742,  0.40484195]]),
 array([[-1.95478732,  0.46564961]]),
 array([[-1.7872537 ,  0.50898799]]),
 array([[-1.62416726,  0.53549442]]),
 array([[-1.46583566,  0.54617144]]),
 array([[-1.31256067,  0.54230812]]),
 array([[-1.16463526,  0.52540206]]),
 array([[-1.02234036,  0.4970906 ]]),
 array([[-0.88594163,  0.4590951 ]]),
 array([[-0.75568617,  0.41317781]]),
 array([[-0.63179919,  0.3611089 ]]),
 array([[-0.514