In [1]:
import numpy as np
import random

In [2]:
def load_data_from_file(file_path):
  data= np.genfromtxt(file_path,skip_header=1,delimiter=",",dtype=None)
  x_features = data[:,:3]
  y_labels = data[:,3:]
  x_features = np.hstack((np.ones((x_features.shape[0],1)),x_features))
  return x_features,y_labels
X,Y = load_data_from_file("advertising.csv")


In [3]:
# Question 2:
features_X,_ = load_data_from_file("advertising.csv")
print(features_X[:5,:])

[[  1.  230.1  37.8  69.2]
 [  1.   44.5  39.3  45.1]
 [  1.   17.2  45.9  69.3]
 [  1.  151.5  41.3  58.5]
 [  1.  180.8  10.8  58.4]]


In [4]:
# Question 3:
_,sales_Y = load_data_from_file("advertising.csv")
print(sales_Y.shape)

(200, 1)


In [5]:
def create_individual(n=4,bound=10):
  individual = [random.uniform(-(bound/2),bound/2) for _ in range(n)]
  return individual
create_individual()

[-2.2428313899308696,
 1.9789007255803508,
 2.1377121171221916,
 -0.7048708777583359]

In [6]:
features_X,sales_Y = load_data_from_file("advertising.csv")
def compute_loss(individual):
  theta = np.array(individual)
  y_hat = np.dot(features_X,theta)
  loss = np.mean((y_hat-sales_Y)**2)
  return loss
def compute_fitness(individual):
  loss = compute_loss(individual)
  return 1/(loss+1)

In [7]:
# Question 4:
features_X , sales_Y = load_data_from_file ("advertising.csv")
individual = [4.09 , 4.82 , 3.10 , 4.02]
fitness_score = compute_fitness( individual )
print ( fitness_score )

1.014222981203215e-06


In [8]:
def crossover(individual1,individual2,crossover_rate=0.9):
  individual1_copy = individual1.copy()
  individual2_copy = individual2.copy()
  for i in range(len(individual1)):
    rand = random.random()
    if rand < crossover_rate:
      individual1_copy[i] = individual2[i]
      individual2_copy[i] = individual1[i]
  return individual1_copy,individual2_copy

In [9]:
individual1 = [4.09 , 4.82 , 3.10 , 4.02]
individual2 = [3.44 , 2.57 , -0.79 , -2.41]
individual1 , individual2 = crossover ( individual1 , individual2 , 2.0)
print (" individual1 : " , individual1 )
print (" individual2 : " , individual2 )

 individual1 :  [3.44, 2.57, -0.79, -2.41]
 individual2 :  [4.09, 4.82, 3.1, 4.02]


In [10]:
def mutate(individual,mutation_rate=0.05):
  individual_copy = individual.copy()
  for i in range(len(individual)):
    rand = random.random()
    if rand < mutation_rate:
      individual_copy[i] = random.uniform(-10,10)
  return individual_copy

In [12]:
# question 6:
before_individual = [4.09,4.82,3.10,4.02]
after_individual = mutate(before_individual,mutation_rate=2.0)
print(before_individual == after_individual)


False


In [13]:
def inittializePopulation(m):
  population = [create_individual() for _ in range(m)]
  return population

In [30]:
def selection(sorted_old_population,m=100):
  index1 = random.randint(0,m-1)
  while True:
    index2 = random.randint(0,m-1)
    if index1 != index2:
      break
  individual_s = sorted_old_population[index1]
  if index2 > index1:
    individual_s = sorted_old_population[index2]
  return individual_s

In [31]:
def create_new_population(old_population,elitism=2,gen=1):
  m = len(old_population)
  sorted_population = sorted(old_population,key=compute_fitness)
  if gen%1 == 0:
    print("Best loss:",compute_loss(sorted_population[m-1]),"with chromsome: ", sorted_population[m-1])
  new_population = old_population.copy()

  while len(new_population) < m-elitism:
    print("run")
    sorted_population = sorted(new_population,key=compute_fitness)
    #selection
    selected_individual = []
    for i in range(m/2):
      selected_individual.append(selection(sorted_population))
    # crossover
    offsprings = []
    for i in range(0,m,2):
      offsprings1,offsprings2 = crossover(selected_individual[i],selected_individual[i+1])
      offsprings.append(offsprings1)
      offsprings.append(offsprings2)
    # mutation
    for i in range(len(offsprings)):
      offsprings[i] = mutate(offsprings[i])
    sorted_offsprings = sorted(offsprings,key=compute_fitness)
    # elitism
    for i in range(elitism):
      new_population[i] = sorted_offsprings[i]
    print(compute_loss(sorted_population[m-1]))
    return new_population, compute_loss(sorted_population[m-1])


In [32]:
# Question 7
individual1 = [4.09 , 4.82 , 3.10 , 4.02]
individual2 = [3.44 , 2.57 , -0.79 , -2.41]
old_population = [ individual1 , individual2 ]
new_population , _ = create_new_population ( old_population , elitism =2 , gen =1)

Best loss: 125375.62399377997 with chromsome:  [3.44, 2.57, -0.79, -2.41]
False


TypeError: cannot unpack non-iterable NoneType object