Bài 1

In [ ]:
import numpy as np

In [ ]:
# Câu 1 A
arr = np.arange(0,10,1)
# Câu 2 D
arr = np.ones((3,3)) >0
arr = np.ones((3,3),dtype=bool)
arr = np.full((3,3),True)

# Câu 3 A
arr = np.arange(0,10)
print(arr[arr%2==1])
#Câu 4 B
arr[arr[arr%2 ==1]] =-1
print(arr)
#Câu 5 B
arr = np.arange(10)
arr_2d = arr.reshape(2,-1)
print(arr_2d)
#Câu 6 A
arr1 = np.arange(10).reshape(2,-1)
arr2= np.repeat(1,10).reshape(2,-1)
new_arr = np.concatenate([arr1,arr2],axis=0)
print(new_arr)
#Câu 7 C
arr1 = np.arange(10).reshape(2,-1)
arr2= np.repeat(1,10).reshape(2,-1)
new_arr = np.concatenate([arr1,arr2],axis=1)
print(new_arr)
#Câu 8 A
arr = np.array([1,2,3])
print(np.repeat(arr,3))
print(np.tile(arr,3))
#Câu 9 C
a = np.array([2,6,1,9,10,3,27])
index = np.where((a>=5)&(a<=10))
print("result",a[index])
#Câu 10 D
def maxx(x,y):
  if x>=y:
    return x
  else:
    return y
a = np.array([5,7,9,8,6,4,5])
b = np.array([6,3,4,8,9,7,1])
pair_max = np.vectorize(maxx,otypes=[float])
print(pair_max(a,b))
#Câu 11 A
print(np.where(a<b,b,a))

[1 3 5 7 9]
[ 0 -1  2 -1  4 -1  6 -1  8 -1]
[[0 1 2 3 4]
 [5 6 7 8 9]]
[[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]
[[0 1 2 3 4 1 1 1 1 1]
 [5 6 7 8 9 1 1 1 1 1]]
[1 1 1 2 2 2 3 3 3]
[1 2 3 1 2 3 1 2 3]
result [ 6  9 10]
[6. 7. 9. 8. 9. 7. 5.]
[6 7 9 8 9 7 5]
